---
name: Template-Context-Cacheable
version: 0.02
author:
  - Walery Studennikov
abstract: profiling/caching-aware version of Template::Context
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.35
provides:
  Template::Context::Cacheable:
    file: lib/Template/Context/Cacheable.pm
    version: 0.02
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
